name: Project3

on:
  push:
    branches:
      - main
    paths:
      - 'Project3/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3    
    - name: Project3 trigger
      run: echo Project3
    - name: directory
      run: ls
