name: Project1

on:
  push:
    branches:
      - main
    paths:
      - 'project1/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3    
    - name: Project1 trigger
      run: echo Project1
    - name: directory
      run: ls
