name: AllProject

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'project1/**'
      - 'Project2/**'
      - 'Project3/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#     - uses: actions/checkout@v3    
#     - name: Project1 trigger
#       run: echo Project1
#     - name: directory
#       run: ls
    - name: branchname
      run: echo ${GITHUB_REF##*/}
    - name: Set env NEED
      run: |
        echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
        if [[ $BRANCH == 'main' ]];  then
            echo "TagName=prod" >> "$GITHUB_ENV"
        else
            echo "TagName=dev" >> "$GITHUB_ENV"
        fi      
    - name: Print
      run:  echo ${TagName}
